from fast_autocomplete import AutoComplete


# Census autocomplete queries
COMMON_QUERIES = [
    "areas with the highest percentage of people with a bachelor's degree",
    "areas with the highest percentage of people with a high school diploma",
    "areas with the highest percentage of people with a master's degree",
    "areas with the highest percentage of people with a professional degree",
    "areas with the highest percentage of people with some college",
    "areas with the highest percentage of people with some high school",
    "areas with long commutes",
    "areas with the most people",
    "areas where the number of people exceeds the national average",
    "areas where the number of people is less than the national average",
    "where am I likely to find the most people working in the arts, entertainment, and recreation industry",
    "where am I likely to find the most people working in the educational services industry",
    "zip code areas with the highest percentage of residents with long commutes of 90 minutes or more",
    "zip code areas with the highest percentage of residents with short commutes of less than 30 minutes",
    "zip code areas with the highest percentage of residents with very long commutes of 120 minutes or more",
    "zctas where the majority of people identify as black or African American",
    "zctas where the majority of people identify as white",
    "zctas where the majority of people identify as Native Hawaiian or Pacific Islander",
    "zctas where the majority of people identify as Asian",
    "zctas where the majority of people identify as American Indian or Alaska Native",
    "What is the distribution of people by age?",
    "Which areas have the highest percentage of people with a bachelor's degree?",
    "What is the percentage of people over 85 in each ZCTA?"
    "What is the male-female ratio in each ZIP code?",
    "How does the population of each ZCTA compare to the population of the US?",
    "Where do people have no heat?",
    "Where do people have no vehicle available?",
    "Where do people have no workers in the household?",
    "What is the racial makeup of each ZCTA?",
    "What ZCTA has the largest population of people who identify as white alone?",
    "What is the percentage of the population in each ZCTA that identifies as two or more races?",
    "Which ZCTA has the largest population of people who identify as Asian alone?",
    "What is the distribution of different racial groups across different ZCTAs?",
    "What is the ratio of white alone to black or African American alone in each ZCTA?",
    "What is the percentage of the population in each ZCTA that identifies as Native Hawaiian or Pacific Islander alone?",
    "What is the percentage of the population in each ZCTA that identifies as \"some other race\" alone?",
    "What is the average commute time?",
    "What is the average commute time for residents in each ZIP code area?",
    "What is the distribution of commute times for residents across different ZIP code areas?",
    "Which zip code areas have the highest percentage of residents with long commutes of 90 minutes or more?",
    "What is the distribution of employment across different industries in each ZIP code?",
    "How does the distribution of employment across different industries vary across zip code areas?",
    "What's the most common industry in each ZIP code area?",
    "Where am I likely to find the most people working in the \"Arts, entertainment, and recreation\" industry?",
    "Where am I likely to find the most people working in the \"Educational services\" industry?",
    "Where am I likely to find the most people working in the \"Health care and social assistance\" industry?",
    "Are there any ZIP code areas that have a particularly high or low concentration of workers in a certain industry?",
    "Where is the highest concentration of workers in the \"Arts, entertainment, and recreation\" industry?",
    "Where is the highest concentration of workers in the \"Educational services\" industry?",
    "Where is the highest concentration of workers in the \"Health care and social assistance\" industry?",
    "Where is the highest concentration of workers in the \"Information\" industry?",
    "Where is the highest concentration of workers in the \"Manufacturing\" industry?",
    "Where is the highest concentration of workers in the \"Professional, scientific, and technical services\" industry?",
    "Where is the highest concentration of workers in the \"Retail trade\" industry?",
    "Where is the highest concentration of workers in the \"Transportation and warehousing\" industry?",
    "Where is the highest concentration of workers in the \"Wholesale trade\" industry?",
    "Where is the lowest concentration of workers in the \"Arts, entertainment, and recreation\" industry?",
    "Where is the lowest concentration of workers in the \"Educational services\" industry?",
    "Where is the lowest concentration of workers in the \"Health care and social assistance\" industry?",
    "Where is the lowest concentration of workers in the \"Information\" industry?",
    "Where is the lowest concentration of workers in the \"Manufacturing\" industry?",
    "Where is the lowest concentration of workers in the \"Professional, scientific, and technical services\" industry?",
    "Where is the lowest concentration of workers in the \"Retail trade\" industry?",
    "Where is the lowest concentration of workers in the \"Transportation and warehousing\" industry?",
    "Where is the lowest concentration of workers in the \"Wholesale trade\" industry?",
    "Where do people make the most money?",
    "Where do people make the least money?",
    "What areas have the largest concentration of the middle class?",
    "Where are the oldest homes?",
    "Where are the newest homes?",
    "Approximately, what is the typical age of homes in each ZIP code area?",
    "Where do households have a mortgage?",
    "Where do households not have a mortgage?",
    "Where do renters exceed homeowners?",
    "Where do homeowners exceed renters?",
    "What is the distribution of homeownership across different ZIP code areas?",
    "What is the distribution of renter-ship across different ZIP code areas?",
    "What is the distribution of median home value across different ZIP code areas?",
    "Where do the humanities majors live?",
    "Where do the social sciences majors live?",
    "Where do the business majors live?",
    "Where do the engineering majors live?",
    "Where do the computer science majors live?",
    "Where do the math majors live?",
    "Where do the physical science majors live?",
    "Where do the life science majors live?",
    "Where do the education majors live?",
    "Where do the health majors live?",
    "Where do the arts majors live?",
    "Where do the agriculture majors live?",
    "Where do people have the highest median income?",
    "Where do most people walk to work?",
    "Where do most people drive to work?",
    "Where do most people take public transportation to work?",
    "Where do most people work from home?",
    "Where is the highest concentration of people who work from home?",
    "What is the median income of people in each ZIP code area?",
    "What is the distribution of median income across different ZIP code areas?",
    "What is the most common mode of transportation?",
    # TODO can we get more of these?
]


def get_autocomplete():
    return AutoComplete(words={
        i: {}
        for i in COMMON_QUERIES
    })
