# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
    -   id: check-added-large-files
    -   id: no-commit-to-branch
        args: ['--branch', 'master']
-   repo: https://github.com/Yelp/detect-secrets
    rev: v1.3.0
    hooks:
    -   id: detect-secrets
        exclude: package.lock.json
        args:
        - "--baseline"
        - ".secrets.baseline"
        - "--exclude-files"
        - "alembic/verions/.*"

