"""Add stripe data to organization

Revision ID: 031edb6348bd
Revises: 66305926d854
Create Date: 2022-11-01 22:34:06.121914

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '031edb6348bd'
down_revision = '66305926d854'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organizations', sa.Column('stripe_subscription_id', sa.String(), nullable=True))
    op.add_column('organizations', sa.Column('stripe_subscription_created_at', sa.DateTime(), nullable=True))
    op.add_column('organizations', sa.Column('stripe_paid_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organizations', 'stripe_paid_at')
    op.drop_column('organizations', 'stripe_subscription_created_at')
    op.drop_column('organizations', 'stripe_subscription_id')
    # ### end Alembic commands ###
