"""Update shapes table

Revision ID: 0fb1541954de
Revises: a1e5f77a6079
Create Date: 2022-07-07 13:40:23.870479

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0fb1541954de'
down_revision = 'a1e5f77a6079'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
