"""Use current time by default

Revision ID: 12711d4e23ef
Revises: bacdc7acec6b
Create Date: 2022-07-07 15:57:31.718339

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12711d4e23ef'
down_revision = 'bacdc7acec6b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
