"""Add backref between users and db creds

Revision ID: 2c15a62f7ebb
Revises: c545e0392ef6
Create Date: 2022-08-05 16:35:54.216063

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c15a62f7ebb'
down_revision = 'c545e0392ef6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
