"""Change users to use string and JWT sub

Revision ID: 48a053a7e015
Revises: 37cd0a912c2d
Create Date: 2022-06-30 14:16:47.411169

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "48a053a7e015"
down_revision = "37cd0a912c2d"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("sub_id", sa.String(), nullable=True))
    op.alter_column(
        "users",
        "id",
        existing_type=sa.INTEGER(),
        type_=sa.INTEGER(),
        existing_nullable=False,
        existing_server_default=sa.text("nextval('users_id_seq'::regclass)"),
    )
    op.create_index(op.f("ix_users_sub_id"), "users", ["sub_id"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_users_sub_id"), table_name="users")
    op.alter_column(
        "users",
        "id",
        existing_type=sa.INTEGER(),
        type_=sa.INTEGER(),
        existing_nullable=False,
        existing_server_default=sa.text("nextval('users_id_seq'::regclass)"),
    )
    op.drop_column("users", "sub_id")
    # ### end Alembic commands ###
