"""Update shape UUID column

Revision ID: 6cf78a62d412
Revises: 45caf0367805
Create Date: 2022-08-30 16:07:50.256359

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = '6cf78a62d412'
down_revision = '45caf0367805'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('shapes',
         'uuid',
         existing_type=postgresql.UUID(as_uuid=True),
         nullable=False,
         server_default=sa.func.gen_random_uuid())
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
    op.alter_column('shapes',
         'uuid',
         existing_type=postgresql.UUID(as_uuid=True),
         nullable=False,
         server_default=None)