"""Update UUID type in shapes

Revision ID: 83b9345798d9
Revises: 92b5ded3466c
Create Date: 2022-07-07 15:25:00.638909

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83b9345798d9'
down_revision = '92b5ded3466c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
