"""Add stripe customer id

Revision ID: 996651db0723
Revises: 35b59fb1b819
Create Date: 2022-11-15 00:44:58.374881

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '996651db0723'
down_revision = '35b59fb1b819'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organizations', sa.Column('stripe_customer_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organizations', 'stripe_customer_id')
    # ### end Alembic commands ###
