"""Update shapes table

Revision ID: a1e5f77a6079
Revises: d780681fa5bb
Create Date: 2022-07-07 13:39:43.449003

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "a1e5f77a6079"
down_revision = "d780681fa5bb"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("shapes", sa.Column("uuid", postgresql.UUID(), nullable=False))
    op.add_column("shapes", sa.Column("deleted_at", sa.DateTime(), nullable=True))
    op.add_column(
        "shapes", sa.Column("deleted_at_by_user_id", sa.Integer(), nullable=True)
    )
    op.add_column(
        "shapes",
        sa.Column("geojson", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    )
    op.drop_index("ix_shapes_id", table_name="shapes")
    op.drop_constraint("shapes_edited_by_user_id_fkey", "shapes", type_="foreignkey")
    op.create_foreign_key(None, "shapes", "users", ["deleted_at_by_user_id"], ["id"])
    op.drop_column("shapes", "shape")
    op.drop_column("shapes", "id")
    op.drop_column("shapes", "edited_by_user_id")
    op.drop_column("shapes", "edited_at")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "shapes",
        sa.Column(
            "edited_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
    )
    op.add_column(
        "shapes",
        sa.Column(
            "edited_by_user_id", sa.INTEGER(), autoincrement=False, nullable=True
        ),
    )
    op.add_column(
        "shapes", sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False)
    )
    op.add_column(
        "shapes",
        sa.Column(
            "shape",
            postgresql.JSONB(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.drop_constraint(None, "shapes", type_="foreignkey")
    op.create_foreign_key(
        "shapes_edited_by_user_id_fkey",
        "shapes",
        "users",
        ["edited_by_user_id"],
        ["id"],
    )
    op.create_index("ix_shapes_id", "shapes", ["id"], unique=False)
    op.drop_column("shapes", "geojson")
    op.drop_column("shapes", "deleted_at_by_user_id")
    op.drop_column("shapes", "deleted_at")
    op.drop_column("shapes", "uuid")
    # ### end Alembic commands ###
