"""Add backref between users and db creds, take 2

Revision ID: a29e32a588d7
Revises: 2c15a62f7ebb
Create Date: 2022-08-05 16:38:34.692730

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a29e32a588d7'
down_revision = '2c15a62f7ebb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.alter_column('db_credentials', 'created_by_user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('db_credentials', 'updated_by_user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(op.f("db_credentials_updated_by_user_id_fkey"), 'db_credentials', type_='foreignkey')
    op.drop_constraint(op.f("db_credentials_created_by_user_id_fkey"), 'db_credentials', type_='foreignkey')
    op.create_foreign_key(op.f("db_credentials_updated_by_user_id_fkey"), 'db_credentials', 'users', ['updated_by_user_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f("db_credentials_created_by_user_id_fkey"), 'db_credentials', 'users', ['created_by_user_id'], ['id'], ondelete='SET NULL')


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("db_credentials_updated_by_user_id_fkey"), 'db_credentials', type_='foreignkey')
    op.drop_constraint(op.f("db_credentials_created_by_user_id_fkey"), 'db_credentials', type_='foreignkey')
    op.create_foreign_key('db_credentials_created_by_user_id_fkey', 'db_credentials', 'users', ['created_by_user_id'], ['id'])
    op.create_foreign_key('db_credentials_updated_by_user_id_fkey', 'db_credentials', 'users', ['updated_by_user_id'], ['id'])
    op.alter_column('db_credentials', 'updated_by_user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('db_credentials', 'created_by_user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
