"""Make it possible to have more than one organization membership and add an active organization marker

Revision ID: a6d124f8653c
Revises: 3f45b1d4e2a5
Create Date: 2022-08-11 00:18:25.512893

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a6d124f8653c'
down_revision = '3f45b1d4e2a5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organization_members', sa.Column('active', sa.Boolean(), nullable=False, default=False))
    op.drop_index('ix_organization_members_user_id', table_name='organization_members')
    op.create_index(op.f('ix_organization_members_user_id'), 'organization_members', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_organization_members_user_id'), table_name='organization_members')
    op.create_index('ix_organization_members_user_id', 'organization_members', ['user_id'], unique=False)
    op.drop_column('organization_members', 'active')
    # ### end Alembic commands ###
