"""Correct tuple issue

Revision ID: bacdc7acec6b
Revises: df6a42021783
Create Date: 2022-07-07 15:55:59.541718

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "bacdc7acec6b"
down_revision = "df6a42021783"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("shapes", sa.Column("updated_at", sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("shapes", "updated_at")
    # ### end Alembic commands ###
