"""Change users back to int

Revision ID: d780681fa5bb
Revises: 48a053a7e015
Create Date: 2022-06-30 14:19:14.183656

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd780681fa5bb'
down_revision = '48a053a7e015'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
