"""Add PostGIS extension

Revision ID: e031e9aba96f
Revises: 6b47ac95f6ae
Create Date: 2022-09-12 22:20:56.084361

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e031e9aba96f'
down_revision = '6b47ac95f6ae'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('shapes', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    conn = op.get_bind()
    conn.execute("CREATE EXTENSION IF NOT EXISTS postgis;")

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('shapes', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    conn.execute("DROP EXTENSION postgis;")
    # ### end Alembic commands ###
