"""Add last login time to users

Revision ID: e7c8682a8b9d
Revises: 25885271fc25
Create Date: 2022-06-24 14:59:40.593332

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "e7c8682a8b9d"
down_revision = "25885271fc25"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("last_login_at", sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "last_login_at")
    # ### end Alembic commands ###
