"""Organization add organization exports

Revision ID: f82aca05f460
Revises: 6b47ac95f6ae
Create Date: 2022-09-13 07:39:28.699089

- Adds column snowflake_account

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f82aca05f460'
down_revision = 'e031e9aba96f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organizations', sa.Column('snowflake_account_id', sa.String(), nullable=True, comment='Snowflake Account ID. Used for data export. See https://docs.snowflake.com/en/user-guide/admin-account-identifier.html.'))
    op.add_column('organizations', sa.Column('s3_export_enabled', sa.Boolean(), nullable=False, server_default=sa.text("FALSE")))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organizations', 'snowflake_account_id')
    op.drop_column('organizations', 's3_export_enabled')
    # ### end Alembic commands ###
