"""Test PATCH /geofencer/shapes/{shape_id}."""
import datetime
from typing import Any, Dict, Optional, cast

import geojson.utils
import randomname
import random
import pytest
from fastapi.testclient import TestClient
from geojson_pydantic import Feature, Polygon

from app.crud.namespaces import create_namespace, get_default_namespace
from app.crud.shape import create_shape, shape_exists
from app.schemas import BaseModel, GeoShape

from .conftest import ConnectionWithDepOverrides
from typing import List


class ShapeTestCase(BaseModel):
    data: Dict[str, Any]
    feature: Feature[Polygon, Dict[str, Any]]
    geojson: Optional[Feature[Polygon, Dict[str, Any]]]


def random_geojson(vertices_min=3, verctices_max=6) -> Feature[Polygon, Dict[str, Any]]:
    return Feature.parse_obj(
        {
            "geometry": geojson.utils.generate_random(
                "Polygon", numberVertices=random.randint(vertices_min, verctices_max)
            ),
            "properties": {
                "name": randomname.get_name(),
            },
        }
    )


SHAPES = [
    {
        "type": "Feature",
        "geometry": {
            "coordinates": [
                [
                    (52.0, -93.0),
                    (69.0, 40.0),
                    (-14.0, 21.0),
                    (-46.0, -32.0),
                    (52.0, -93.0),
                ]
            ],
            "type": "Polygon",
        },
        "properties": {"name": "pink-objective"},
    },
    {
        "type": "Feature",
        "geometry": {
            "coordinates": [
                [
                    (-13.0, 26.0),
                    (-93.0, -9.0),
                    (-14.0, -70.0),
                    (32.0, -18.0),
                    (45.0, 43.0),
                    (-13.0, 26.0),
                ]
            ],
            "type": "Polygon",
        },
        "properties": {"name": "convoluted-sledder"},
    },
    {
        "type": "Feature",
        "geometry": {
            "coordinates": [
                [(42.0, 49.0), (-116.0, 26.0), (12.0, -36.0), (42.0, 49.0)]
            ],
            "type": "Polygon",
        },
        "properties": {"name": "isobaric-concentration"},
    },
    {
        "type": "Feature",
        "geometry": {
            "coordinates": [[(7.0, -8.0), (27.0, 52.0), (-45.0, -9.0), (7.0, -8.0)]],
            "type": "Polygon",
        },
        "properties": {"name": "short-bulldozer"},
    },
    {
        "type": "Feature",
        "geometry": {
            "coordinates": [
                [
                    (9.0, -54.0),
                    (71.0, -32.0),
                    (82.0, 59.0),
                    (-1.0, 14.0),
                    (-73.0, 31.0),
                    (-74.0, -54.0),
                    (9.0, -54.0),
                ]
            ],
            "type": "Polygon",
        },
        "properties": {"name": "thundering-use"},
    },
    {
        "type": "Feature",
        "geometry": {
            "coordinates": [
                [
                    (10.0, 75.0),
                    (-32.0, 24.0),
                    (-72.0, -32.0),
                    (-12.0, -90.0),
                    (49.0, -37.0),
                    (86.0, 30.0),
                    (10.0, 75.0),
                ]
            ],
            "type": "Polygon",
        },
        "properties": {"name": "several-sword"},
    },
]
"""
Random shapes generated by::

    [random_geojson().dict() for _ in range(6)]
"""


def setup(alice_conn: ConnectionWithDepOverrides, bob, carlos):
    # data
    _ = alice_conn
    example_com_namespace = get_default_namespace(
        _.conn, organization_id=_.organization.id
    )
    example_net_namespace = get_default_namespace(
        _.conn, organization_id=carlos.organization.id
    )
    new_namespace = create_namespace(
        _.conn, "Namespace 1", user_id=_.user.id, organization_id=_.organization.id
    )
    # Alice shapes in default
    shapes = []

    def _create_shape(i: int, **kwargs):
        kwargs = {
            "user_id": _.user.id,
            "organization_id": _.organization.id,
            "namespace_id": example_com_namespace.id,
            **kwargs,
        }
        shapes.append(
            create_shape(_.conn, geojson=Feature.parse_obj(SHAPES[i]), **kwargs)
        )

    # 2 shapes owned by alice in default namespace
    # 1 shapes owned by alice in new namespace
    # 1 shape owned by bob
    # 1 shape owned by carlos

    # Alice shapes in default namespace
    _create_shape(0)
    _create_shape(1)
    # Alice shape in new namespace
    _create_shape(2, namespace_id=new_namespace)
    # Bob shape in default namespace
    _create_shape(3, user_id=bob.id, namespace_id=example_com_namespace)
    # Carlos shape
    _create_shape(4, user_id=carlos.id, namespace_id=example_net_namespace)

    return {
        "namespaces": {
            "example.com default": example_com_namespace,
            "example.com new": new_namespace,
            "example.net default": example_net_namespace,
        },
        "users": {"alice": _.user, "bob": bob, "carlos": carlos},
        "organizations": {"example.com": _.organization, "example.net": None},
        "shapes": shapes,
    }


# Alice: 5 shapes: 3 in default, 2 non-default
# Bob: 1 shape default, 0 shape non-default - same org
# Carlos: 1 shape - diff org

# def test_read_shape_self(
#     client: TestClient, alice_conn: ConnectionWithDepOverrides, bob: UserOrganization
# ):
#     shape = create_shape(
#         alice_conn.conn,
#         user_id=alice_conn.user.id,
#         organization_id=alice_conn.organization.id,
#         geojson=random_geojson(),
#     )
#     with alice_conn.dep_overrides:
#         response = client.get(f"/geofencer/shapes/{shape.uuid}")
#         body = response.json()
#         assert_ok(response)
#         assert GeoShape.parse_obj(body) == shape


# def test_read_shape_not_exists(
#     client: TestClient, alice_conn: ConnectionWithDepOverrides
# ):
#     # don't create any shapes
#     shape_id = uuid.uuid4()
#     with alice_conn.dep_overrides:
#         response = client.get(f"/geofencer/shapes/{shape_id}")
#         assert_status_code(response, status.HTTP_404_NOT_FOUND)


# def test_read_shape_other_user_same_org(
#     client: TestClient, alice_conn: ConnectionWithDepOverrides, bob: UserOrganization
# ):
#     shape = create_shape(
#         alice_conn.conn,
#         user_id=bob.user.id,
#         organization_id=bob.organization.id,
#         geojson=random_geojson(),
#     )
#     with alice_conn.dep_overrides:
#         response = client.get(f"/geofencer/shapes/{shape.uuid}")
#         body = response.json()
#         assert_ok(response)
#         assert GeoShape.parse_obj(body) == shape


# def test_read_shape_other_org(
#     client: TestClient, alice_conn: ConnectionWithDepOverrides, carlos: UserOrganization
# ):
#     shape = create_shape(
#         alice_conn.conn,
#         user_id=carlos.user.id,
#         organization_id=carlos.organization.id,
#         geojson=random_geojson(),
#     )
#     with alice_conn.dep_overrides:
#         response = client.get(f"/geofencer/shapes/{shape.uuid}")
#         assert_status_code(response, status.HTTP_404_NOT_FOUND)


# def test_create_shape(client: TestClient, alice_conn: ConnectionWithDepOverrides):
#     data = GeoShapeCreate(geojson=random_geojson())
#     with alice_conn.dep_overrides:
#         response = client.post("/geofencer/shapes", json=data.dict())
#         print(response.json())
#         assert_ok(response)
#         actual = GeoShape.parse_obj(response.json())
#         assert actual.geojson.geometry == data.geojson.geometry
#         assert actual.geojson.properties == data.geojson.properties
#     # check that it was created in the database
#     assert shape_exists(alice_conn.conn, actual.uuid)


# # def test_get_all_shapes(
# #     client: TestClient,
# #     alice_conn: ConnectionWithDepOverrides,
# #     carlos: UserOrganization,
# #     bob: UserOrganization,
# # ):
# #     shape = create_shape(
# #         alice_conn.conn,
# #         user_id=carlos.user.id,
# #         organization_id=carlos.organization.id,
# #         geojson=random_geojson(),
# #     )
# #     with dep_override_factory(user_id):
# #         response = client.get(f"/geofencer/shapes?user=true")
# #         assert_ok(response)
# #         body = response.json()
# #         assert body
# #         assert {shape["uuid"] for shape in body} == user_shapes


# # def test_get_all_shapes_by_organization(client, connection, dep_override_factory):
# #     user_id = 1
# #     organization_id = "5b706ffe-9608-4edd-bb00-ab9cbcb7384f"
# #     user_shapes = {
# #         "4f974f2d-572b-46f1-8741-56bf7f357d12",
# #         "8073a55a-98d4-43a7-a1fa-eefab3980f7a",
# #         "59955baf-9ffb-4c63-a6fa-6e790286d307",
# #         "88707385-829f-4edd-9860-927675a48c70",
# #         "a5da808f-b717-41cb-a566-603674172bf2",
# #         "45cd0ce9-7e2f-47cc-922a-fb02b0cf115b",
# #         "13c0b2ee-dada-421b-92eb-f756ef79d883",
# #     }

# #     with dep_override_factory(user_id):
# #         response = client.get(f"/geofencer/shapes")
# #         assert_ok(response)
# #         body = response.json()
# #         assert body
# #         assert {shape["uuid"] for shape in body} == user_shapes


# # def test_create_shape(client, connection, dep_override_factory):
# #     user_id = 1
# #     shape = GeoShapeCreate(
# #         name="fuchsia-auditor",
# #         geojson=Feature(
# #             id="1",
# #             type="Feature",
# #             geometry=Point(type="Point", coordinates=(-6.364088, -65.21654)),
# #             properties={"test": "test"},
# #         ),
# #     )

# #     uuid = None

# #     with dep_override_factory(user_id):
# #         response = client.post(f"/geofencer/shapes", json=shape.dict())
# #         assert_ok(response)
# #         body = response.json()
# #         uuid = body["uuid"]
# #         assert body
# #         assert uuid
# #         assert body["name"] == shape.name
# #         assert (
# #             tuple(body["geojson"]["geometry"]["coordinates"])
# #             == shape.geojson.geometry.dict()["coordinates"]
# #         )
# #         assert body["geojson"]["geometry"]["type"] == shape.geojson.geometry.type

# #     assert (
# #         connection.execute(
# #             text("SELECT uuid FROM shapes WHERE uuid = :uuid"), {"uuid": uuid}
# #         ).rowcount
# #         == 1
# #     )


# # def test_bulk_create_shapes(client, connection, dep_override_factory):
# #     user_id = 1
# #     shapes = [
# #         GeoShapeCreate(
# #             name="fuchsia-auditor",
# #             geojson=Feature(
# #                 id="1",
# #                 type="Feature",
# #                 properties={"test": 1},
# #                 geometry=Point(type="Point", coordinates=(-6.364088, -65.21654)),
# #             ),
# #         ),
# #         GeoShapeCreate(
# #             name="acute-vignette",
# #             geojson=Feature(
# #                 id="2",
# #                 type="Feature",
# #                 properties={"test": 1},
# #                 geometry=Point(type="Point", coordinates=(-20.586622, 53.832401)),
# #             ),
# #         ),
# #     ]

# #     with dep_override_factory(user_id):
# #         response = client.post(
# #             f"/geofencer/shapes/bulk", json=[s.dict() for s in shapes]
# #         )
# #         assert_ok(response)
# #         body = response.json()
# #         assert body
# #         assert body["num_shapes"] == 2

# #     for shp in shapes:
# #         assert (
# #             connection.execute(
# #                 text("SELECT uuid FROM shapes WHERE name = :name"),
# #                 {"name": shp.name},
# #             ).rowcount
# #             == 1
# #         )

# import time

# OLD_SHAPE =

# SHAPE_UPDATES = [
#     {"name": "This is a new name"},
#     {"properties": {"foo": 1, "bar": 2}},
#     {"geojson": random_geojson()},
#     {}
# ]

# @pytest.fixture(params=["a", "b", "c"])
# def shape_update(request):
#     return request.param


# def test_patch_shape(client: TestClient, alice_conn: ConnectionWithDepOverrides):
#     # data = shape to create
#     _ = alice_conn

#     # create a new new random shape
#     shape = create_shape(
#         _.conn,
#         user_id=_.user.id,
#         organization_id=_.organization.id,
#         geojson=random_geojson(),
#     )
#     shape_id = shape.uuid

#     # what updates are being applied
#     new_name = "This is a new name"
#     data = {"name": new_name}

#     # This is the expected result given shape + update
#     expected = copy.copy(shape)
#     shape.geojson.properties = shape.geojson.properties or {}
#     shape.geojson.properties["name"] = new_name
#     with _.dep_overrides:
#         response = client.patch(f"/geofencer/shapes/{shape_id}", json=data)
#         assert_ok(response)
#         actual = GeoShape.parse_obj(response.json())
#         assert actual.geojson == expected.geojson
#         assert actual.namespace_id == expected.namespace_id
#         assert actual.uuid == expected.uuid
#         assert actual.updated_at > expected.updated_at
#         assert actual.created_at == expected.created_at
#     # check that it was created in the database
#     assert shape_exists(_.conn, actual.uuid)
