# fly.toml file generated for mercator-dd-agent on 2022-10-18T21:48:55-05:00

app = "mercator-dd-agent"
kill_signal = "SIGINT"
kill_timeout = 5

[env]
  DD_APM_ENABLED = "true"
  DD_APM_NON_LOCAL_TRAFFIC = "true"
  DD_DOGSTATSD_NON_LOCAL_TRAFFIC = "true"
  DD_LOGS_ENABLED = "true"
  DD_ENV = "staging"
  DD_SITE = "datadoghq.com"
  DD_USE_DOGSTATSD = "true"

[build]
  image = "datadog/agent:7"

[[services]]
  internal_port = 8125
  protocol = "udp"
  [[services.ports]]
    port = 8125

[[services]]
  internal_port = 8126
  protocol = "tcp"
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 8126

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 8126

  [[services.tcp_checks]]
    grace_period = "30s"
    interval = "15s"
    restart_limit = 0
    timeout = "10s"
