version: "3.9"
services:
  osm:
    build: .
    container_name: osm-postgis
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - OSM2PGSQL_EXTRA_ARGS=--bbox -122.50387653708461,-122.16330036520961,37.73150183343975,37.895865835843146
    ports:
      - '5438:5432'
    volumes:
      - osm-data:/var/lib/postgresql/data
    command: "postgres -c max_wal_size=10GB -c work_mem=2GB"
volumes:
  osm-data:
