# fly.toml file generated for geox-hightouch-tunnel on 2022-08-28T12:38:17-07:00

app = "geox-hightouch-tunnel"

kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[experimental]
  auto_rollback = true
