# geox api backend dev container
#
# Unlike prod this:
# - uses local files
# - runs uvicorn with --reload

ARG PYTHON_VERSION=3.9
FROM python:${PYTHON_VERSION}

VOLUME /webapp

# Dockerfile for mercator FastAPI backend.
# Derived from https://fastapi.tiangolo.com/deployment/docker/?h=containers

# TODO: find better way to share code between dev and prod containers

WORKDIR /code
COPY ./requirements.txt /code/requirements.txt
RUN python -m pip install --no-cache-dir --upgrade pip
RUN pip install --no-cache-dir --upgrade -r /code/requirements.txt
COPY  ./requirements-dev.txt /code/requirements-dev.txt
RUN pip install --no-cache-dir --upgrade -r /code/requirements-dev.txt

WORKDIR /webapp
EXPOSE 8080
CMD ["./start.sh"]
