version: "3.3"
services:

  db:
    image: "postgis/postgis:14-3.2-alpine"
    env_file: ./.env.docker
    container_name: geox-api-db
    volumes:
      - geox-app-db-data:/var/lib/postgresql/data/pgdata
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata

  queue:
    container_name: geox-api-queue
    image: redis
    env_file: ./.env.docker

  # Backend app
  app:
    container_name: geox-api-app
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        - git_commit_hash=${GIT_COMMIT}
    depends_on:
      - db
      - queue
    # See https://docs.docker.com/compose/environment-variables/#set-environment-variables-with-docker-compose-run
    env_file: ./.env.docker
    environment:
      APP_ENV: production
      ENV_FILE: .env.docker
      POSTGRES_SERVER: db
      REDIS_CONNECTION: 'redis://queue:6379/0'
      DD_APM_ENABLED: false
      # needed to avoid reading .env file
      OVERMIND_SKIP_ENV: 1
    logging:
      options:
        tag: ""
    ports:
      - "8080:8080"

volumes:
  geox-app-db-data:
