version: "3.3"
services:

  # Backend app
  app:
    container_name: geox-api-app-dev
    build:
      context: .
      dockerfile: ./Dockerfile.dev
      args:
      - git_commit_hash=${GIT_COMMIT}
    volumes:
    - ".:/webapp"
    environment:
    - "APP_RELOAD=1"

  db:
    container_name: geox-api-db-dev
    environment:
    - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
    - "geox-app-db-data-dev:/var/lib/postgresql/data/pgdata"

  celeryworker:
    container_name: geox-api-celeryworker-dev
    volumes:
    - ".:/webapp"

  queue:
    container_name: geox-api-dev-queue

volumes:
  geox-app-db-data-dev:
