version: "3.3"
services:

  # Backend app
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    depends_on:
      - db
    # See https://docs.docker.com/compose/environment-variables/#set-environment-variables-with-docker-compose-run
    env_file: ./.env.docker
    environment:
        ENV_FILE: ./.env.docker
    ports:
      - "8080:8080"
