# Builds App for local development
ARG PYTHON_VERSION=3.9
FROM python:${PYTHON_VERSION}

VOLUME /webapp

# TODO: find better way to share code between dev and prod containers
WORKDIR /code
COPY ./requirements.txt ./requirements-dev.txt /code/
RUN python -m pip install --no-cache-dir --upgrade pip==22.1.2 && \
    pip install --no-cache-dir --upgrade -r /code/requirements.txt && \
    pip install --no-cache-dir --upgrade -r /code/requirements-dev.txt

WORKDIR /webapp
EXPOSE 8080
ENV PYTHONPATH=/webapp
CMD ["./worker-start.sh"]
