# fly.toml file generated for restless-rain-538 on 2022-06-10T13:27:43-07:00

app = "restless-rain-538"

kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[env]
  PORT = "8080"
  BACKEND_CORS_ORIGINS = "[\"*\"]"
  APP_ENV = "production"

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[metrics]
  path = "/metrics"
  port = 8080

[[services]]
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  script_checks = []

  [services.concurrency]
    hard_limit = 50
    soft_limit = 40
    type = "connections"

  [[services.http_checks]]
    grace_period = "10s"
    interval = 5000
    method = "get"
    path = "/health"
    protocol = "http"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"

[[statics]]
  guest_path = "/app/public"
  url_prefix = "/static/"
