# fly.toml file generated for hidden-sun-7397 on 2022-10-06T14:55:07-07:00

app = "hidden-sun-7397"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[env]
  APP_ENV = "staging"
  BACKEND_CORS_ORIGINS = "[\"*\"]"
  PORT = "8080"
  APP_CACHE__ENABLED = true
  APP_CACHE__TIMEOUT = 60

[metrics]
  path = "/metrics"
  port = 8080

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[[services]]
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 50
    soft_limit = 40
    type = "connections"

  [[services.http_checks]]
    grace_period = "10s"
    interval = 5000
    method = "get"
    path = "/health"
    protocol = "http"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"

[[statics]]
  guest_path = "/app/public"
  url_prefix = "/static/"
