[tool.isort]
py_version = 39
skip_gitignore = true
skip_glob = ["env/**", "alembic/versions/**"]
profile = "black"

[tool.black]
line-length = 88
target-version = ['py39']
exclude = "env/|alembic/versions"

[tool.mypy]
python_version = "3.9"
exclude = '''(?x)
    ^env/
    | ^alembic/versions
'''
plugins = ["pydantic.mypy", "sqlmypy"]
ignore_missing_imports = true
allow_untyped_defs = true

