[tool.isort]
py_version = 39
skip_gitignore = true
skip_glob = ["env/**", "alembic/versions/**"]
profile = "black"

[tool.black]
line-length = 88
target-version = ['py39']
exclude = "env/|alembic/versions"
