version: "3.9"
services:
  osm:
    image: mercator.tech/osm-db
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - osm2pgsql_style=style.lua
        - osm2pgsql_input_data=osm.pbf
    container_name: osm-postgis
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5438:5432'
    volumes:
      - osm-data:/var/lib/postgresql/data
    command: "postgres -c maintenance_work_mem=2GB -c shared_buffers=1GB -c work_mem=50MB -c max_wal_size=4GB"
volumes:
  osm-data:
