# fly.toml file generated for mercator-fly-log-shipper on 2022-09-15T20:56:25-05:00

app = "mercator-fly-log-shipper"

[env]
  ORG = "mercator"
  SUBJECT = "logs.>"

[metrics]
  path = "/metrics"
  port = 9598
