from app.data.presets import presets
from app.core.jinja_utils import ENV
import jinja2 as j2

template = ENV.from_string("""
    -- generated by create_presets.py
    -- from presets.json

    DROP TABLE IF EXISTS {{ tablename }};
    CREATE TABLE IF NOT EXISTS {{ tablename }} (
        osm_id BIGINT NOT NULL, -- REFERENCES osm(osm_id, osm_type),
        category TEXT NOT NULL,
        PRIMARY KEY (osm_id, osm_type, category)
    );

    BEGIN;

    {% for category, preset in presets.items() %}
    INSERT INTO {{ tablename }} (osm_id, osm_type, category)
    SELECT osm_id, osm_type, '{{ category }}'
    FROM osm
    WHERE
    TRUE
    {%- for tag, value in preset.tags.items() %}
    {%- if value == "*" %}
    AND tags ? {{ tag | squote }}
    {%- else %}
    AND tags ->> {{ tag | squote }} = {{ value | squote }}
    {%- endif %}
    {%- endfor %}
    AND (
        FALSE
        {%- if 'area' in preset.geometry %}
        OR (osm_type = 'W' AND GeometryType(geom) = 'POLYGON')
        {%- endif %}
        {%- if 'line' in preset.geometry %}
        OR (osm_type = 'W' AND GeometryType(geom) = 'LINESTRING')
        {%- endif %}
        {%- if 'vertex' in preset.geometry or 'point' in preset.geometry %}
        OR (osm_type = 'N')
        {%- endif %}
        {%- if 'relation' in preset.geometry %}
        OR (osm_type = 'R')
        {%- endif %}
    );
    {% endfor %}

    CREATE INDEX IF NOT EXISTS {{ tablename }}_category_idx ON {{ tablename }} (category);
    CREATE INDEX IF NOT EXISTS {{ tablename }}_osm_id_osm_type_idx ON {{ tablename }} (osm_id, osm_type);

    COMMIT;
    """)

from itertools import islice

def main() -> None:
    tablename = "category_membership"
    sql = template.render(tablename=tablename, presets=presets)
    print(sql)

if __name__ == "__main__":
    main()