



[tool.pylint."messages control"]
disable = ["too-few-public-methods", "too-many-arguments", "fixme"]
enable = []

[tool.pylint]
ignore-long-lines = "^(\\s*(# ).*|.*<https?://.*)$"
max-line-length = 100
good-names = ["m", "i", "f", "c", "nc"]


[tool.pytest.ini_options]
asyncio_mode = "strict"

[tool.isort]
py_version = 310
skip_gitignore = true
skip_glob = ["env/**", "alembic/versions/**"]
profile = "black"

[tool.black]
line-length = 100
target-version = ['py310']
exclude = "env/|alembic/versions|\\.ipynb$|\\.ipynb_checkpoints/"

[tool.mypy]
python_version = "3.10"
exclude = '''(?x)
    ^env/
    | ^alembic/versions
'''
plugins = ["pydantic.mypy", "sqlalchemy.ext.mypy.plugin"]
ignore_missing_imports = true
allow_untyped_defs = false


[tool.pyright]
include = ["app", "test", "cli"]
exclude = ["**/node_modules",
    "**/__pycache__",
    "**/.ipynb_checkpoints"
]
pythonVersion = "3.10"
reportGeneralTypeIssues = false
