# Docs for deploying fly.io apps with github actions:
# https://fly.io/docs/app-guides/continuous-deployment-with-github-actions/#speed-run-your-way-to-continuous-deployment
name: Fly Deploy Staging
env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
on:
  pull_request:
    types:
      - closed
jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --build-arg git_commit_hash=$GITHUB_SHA --dockerfile="Dockerfile" --remote-only --config fly.staging.toml --app hidden-sun-7397
        working-directory: geox-api
  # Add a notice to slack that the branch has published
  notify_merged_pull_request:
    name: Notify Slack on merged pull requests
    id: slack
    runs-on: ubuntu-latest
    needs: deploy
    steps:
      - uses: slackapi/slack-github-action@v1.18.0
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.DEPLOY_TO_STAGING_SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
        with:
          payload: |
            {
              "text": "GitHub Action build result: ${{ job.status }}\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}",
            }
