name: Test-Backend-App
on: [push]
env:
  AUTH0_CLIENT_ID: ${{ secrets.AUTH0_CLIENT_ID }}
  AUTH0_CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
  AUTH0_DOMAIN: ${{ secrets.AUTH0_DOMAIN }}
  AUTH0_API_AUDIENCE: ${{ secrets.AUTH0_API_AUDIENCE }}
  APP_SECRET_KEY: ${{ secrets.APP_SECRET_KEY }}
  AUTH0_MACHINE_CLIENT_ID: ${{ secrets.AUTH0_MACHINE_CLIENT_ID }}
  AUTH0_MACHINE_CLIENT_SECRET: ${{ secrets.AUTH0_MACHINE_CLIENT_SECRET }}
jobs:
  Lint-Code:
    runs-on: ubuntu-latest
    environment: geox-api-ci
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          cache: 'pip'
      - name: Install dependencies
        run: sudo apt-get install -y shellcheck
      - name: Install python requirements
        run: python -m pip install --upgrade wheel pip
      - name: Install python requirements
        run: pip install -r ./geox-api/requirements.txt
      - name: Install python dev requirements
        run: pip install -r ./geox-api/requirements-dev.txt
      - name: Run all linting
        run: ./bin/lint.sh
        working-directory: geox-api
  Test-Code:
    # You must use a Linux environment when using service containers or container jobs
    runs-on: ubuntu-latest
    environment: geox-api-ci
    env:
      POSTGRES_USER: "postgres"
      POSTGRES_DB: "geox"
      POSTGRES_SERVER: "localhost"
      POSTGRES_PASSWORD: "postgres"
    # Service containers to run with `runner-job`
    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: postgis/postgis
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        env:
          POSTGRES_USER: "postgres"
          POSTGRES_DB: "geox"
          POSTGRES_SERVER: "localhost"
          POSTGRES_PASSWORD: "postgres"
          PGUSER: "postgres"
        ports:
          # Maps tcp port 5432 on service container to the host
          - 5432:5432
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          cache: 'pip'
      - name: Install python requirements
        run: python -m pip install --upgrade wheel pip
      - name: Install python requirements
        run: pip install -r ./geox-api/requirements.txt
      - name: Install python dev requirements
        run: pip install -r ./geox-api/requirements-dev.txt
      - run: ./tests-start.sh
        working-directory: geox-api
        env:
          POSTGRES_CONNECTION: "postgresql+psycopg2://postgres:postgres@localhost:5432/geox"
